### PR TITLE
Problems to recollet errors in HttpClientModule Angular 4.3+

### PR DESCRIPTION
**Pull request by SamazoOo**
I think that should solve the problems that I'm having to recollet error with HttpClientModule, the request is returning HttpResponseBase.

### CODE REVIEW

**Comment by RSuter** [comment]
Thanks for the PR. My only question is, whether we should really use instanceof? Does it work in all browsers, etc.?

**Comment by SamazoOo** [comment]
I've just tested in IE, Edge, chrome and firefox and there are no problems, it's working. I forgot to include HttpResponseBase in imports, but I did it.

Thanks for the this amazing product

**Comment by RSuter** [comment]
I didn't check it, but why is this helping? Does HttpResponseBase have all needed properties or may they be undefined?

**Comment by RSuter** [comment]
I've updated the templates, please retest with the latest CI artifacts: https://ci.appveyor.com/project/rsuter/nswag-25x6o/build/artifacts

**Comment by SamazoOo** [comment]
It's working for me!

**Pull request merged**
