### PR TITLE
Optional/required parameters: Use RequireParametersWithoutDefault fallback setting and API Explorer

### PR DESCRIPTION
**Pull request by RSuter**
Closes https://github.com/RSuter/NSwag/issues/1599

### CODE REVIEW

**Comment by RSuter** [comment]
I've added tests for complex body parameters... check my controller in the PR. The tests now reflect the current implementation but they are not how you'd expect them, right?

**Comment by scottdewald** [comment]
> I've added tests for complex body parameters... check my controller in the PR. The tests now reflect the current implementation but they are not how you'd expect them, right?

Looks great. Thanks a lot!

**Comment by RSuter** [comment]
Yeah, but the problem is that this is not how api explorer reports isrequired (currently required = !has default). And the goal is to completely use api explorer...

**Comment by RSuter** [comment]
IMPORTANT: This is not about whether FromBody is required or not but about if a body parameter is required or not...

**Comment by RSuter** [comment]
If I enable api explorer required handling, body parameters are always required. @rynowak is there way to mark body parameters as optional, e.g. [BindOptional]?

**Comment by rynowak** [comment]
With `[ApiController]` body are parameters are required and that's enforced by the framework. We didn't add a way to make body parameters optional because no one has asked for it.

**Comment by RSuter** [comment]
@scottdewald please check PR again, it now adds body parameter tests (always required in the tests) plus a new setting for the "only parameters with default are optional" fallback... is this what you'd expect?

**Pull request merged**
