### PR TITLE
Add support for .NET Core 2.0

### PR DESCRIPTION
**Pull request by RSuter**

### CODE REVIEW

**Comment by gozdebozkurt** [comment]
@RSuter is there any progress on [getting the build to work](https://ci.appveyor.com/project/rsuter/nswag-25x6o/history)?

Is there any way we can help?

If you shared your `appveyor.yml` we could work on this in our fork (or maybe even keep in the repo, as described in [your Settings section](https://ci.appveyor.com/project/rsuter/nswag-25x6o/settings/yaml))

**Comment by RSuter** [comment]
It seems that the VM is missing the latest .NET Core version... I'm just looking into it.

**Comment by RSuter** [comment]
The appveyor.yml is

```
version: '{build}'
branches:
  except:
  - release
image: Visual Studio 2017 Preview
configuration: Release
platform: Any CPU
before_build:
- cmd: >-
    npm --prefix "src\NSwag.Integration.TypeScriptWeb" install "src\NSwag.Integration.TypeScriptWeb"


    nuget restore src\NSwag.sln -NoCache

    dotnet restore src\NSwag.sln --no-cache
build:
  project: src\NSwag.sln
  verbosity: minimal
after_build:
- cmd: >-
    nuget pack src/NSwag.MSBuild/NSwag.MSBuild.nuspec

    nuget pack src/NSwagStudio.Chocolatey/NSwagStudio.nuspec
test:
  categories:
    except:
    - integration
artifacts:
- path: '*.nupkg'
- path: src\NSwagStudio.Installer\bin\Release\NSwagStudio.msi
  name: NSwagStudio.msi
- path: src\NSwagStudio\bin\Release
  name: NSwag
- path: src\NSwagStudio\Properties\AssemblyInfo.cs
- path: src/NSwag**/*.nupkg
deploy:
- provider: NuGet
  server: https://www.myget.org/F/nswag-ci/api/v2/package
  api_key:
    secure: ***
  skip_symbols: true
  on:
    branch: master
```

**Comment by gozdebozkurt** [comment]
Could you give us [secure variable](https://www.appveyor.com/docs/build-configuration/#secure-variables) (encrypted) for api key?

**Comment by RSuter** [comment]
Its ok for now, ci build is working now... Please open a new issue and i can post the current appveyor.yml and secure var there...

**Comment by RSuter** [comment]
v11.5.0

**Pull request merged**
