### PR TITLE
Allow variables to contain backslashes

### LINKED ISSUE #1251: Combining MSBuild and nswag.json variables might create invalid json
I was trying to use Variables and NSwag.json from MSBuild like this:

```
<Exec Command="$(NSwagExe_Core20) webapi2swagger run nswag.json /variables:"assembly=$(TargetPath)" />
```

This will end in Invalid JSON, since $(TargetPath) naturally contains "\" which is needed to be escaped in JSON.

My proposals to solve this are:
- Either provide a way to pass overrides for nswag.json (e.g: `/overrides:"path:in:json=newValue"`) (which is still problematic, because multiple overrides have to be separated by something, which might also be part of newValue)
 - Or allow automatic string escaping in nswag.json (e.g: `nswag.exe run nswag.json /escapeVars:true /variable:"foo=b\ar"`)

I assume the last one would be easier to implement in the variable Substitution, and with some advice where to look, i'd also provide a PR for that.

### PR DESCRIPTION
**Pull request by glatzert**
Fixes #1251

### CODE REVIEW

**Comment by RSuter** [comment]
Currently we do not have any unit tests which cover this...

**Comment by glatzert** [comment]
That somewhat makes them all green as well 😶

**Comment by RSuter** [comment]
Yep. I've added another JsonConvert.ToString() to the default variables...

**Comment by glatzert** [comment]
I somewhat forgot that 👍

**Comment by RSuter** [comment]
Is this a regression of this PR?
https://github.com/RSuter/NSwag/issues/1253#issuecomment-378261857

**Pull request merged**
