### PR TITLE
Add support for using swagger `operationId` property as route name in `RouteAttribute`s of generated controllers

### LINKED ISSUE #1452: Add support for using swagger `operationId` property as route name in `RouteAttribute`s of generated controllers
Add support for using swagger `operationId` property as route name in `RouteAttribute`s of generated controllers. It would be nice to use the operation id when forming links using the [`UrlHelper`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.routing.urlhelper?view=aspnetcore-2.1) class. Can this be achieved using custom templates? If so, can you provide some guidance in doing so?

### PR DESCRIPTION
**Pull request by goldsam**
This PR resolves #1452

### CODE REVIEW

**Comment by goldsam** [comment]
I introduce a new [`RouteNamingStrategy`](https://github.com/goldsam/NSwag/blob/2f79f3a0c4cac8609f6cdd147d0e2204f086b071/src/NSwag.CodeGeneration.CSharp/SwaggerToCSharpControllerGeneratorSettings.cs#L53) enum property to `SwaggerToCSharpControllerGeneratorSettings` which defaults to [`CSharpControllerRouteNamingStrategy.None`](https://github.com/goldsam/NSwag/blob/2f79f3a0c4cac8609f6cdd147d0e2204f086b071/src/NSwag.CodeGeneration.CSharp/Models/CSharpControllerRouteNamingStrategy.cs#L16) to maintain backwards compatibility. No value for `Name` is output for `RoutedAttribute`s for generated output if when this settings is `CSharpControllerRouteNamingStrategy.None` or if no route name can be resolved.

**Comment by RSuter** [comment]
Is it ok for you if i change the headers to the same as the other files?

**Comment by goldsam** [comment]
Thats fine.

**Comment by goldsam** [comment]
Is there anything I can do to help get this to release faster? I could add the setting to the UI if you haven't had time yet to do that.

**Comment by RSuter** [comment]
Thanks for the PR!

**Pull request merged**
