### PR TITLE
Add content type to file parameters;

### PR DESCRIPTION
**Pull request by mihailpd**
https://github.com/RSuter/NSwag/issues/816

Need some refactoring to avoid code duplication

### CODE REVIEW

**Comment by RSuter** [comment]
Still WIP?

**Comment by RSuter** [comment]
I think its fine as is...

**Comment by RSuter** [comment]
Added missing braces, regenerated clients... thanks for the PR!

**Comment by mihailpd** [comment]
@RSuter thanks! Please let me know when it will be released

**Comment by RSuter** [comment]
v12.0.11

**Pull request merged**
