### PR TITLE
Improved exception handling in middlewares

### PR DESCRIPTION
**Pull request by prochnowc**
- Do not catch exception, leave handling to framework
- Enables use of developer exception page
- Correctly responds with HTTP 500 in case of failure
- Added cache timeout when schema generation threw an exception

Solves #1144.

### CODE REVIEW

**Comment by RSuter** [comment]
Thanks for the pr. Looks good.

**Comment by prochnowc** [comment]
Glad that i could help.

**Comment by Seabizkit** [comment]
so how the hell do you stop middle where from caching swagger.json, aka api is deployed.... which goes through cloud-flare, how do i add headers to the swagger ui, to stop this from being cached. version lastest.. V5-r4, does not seem possible.

**Comment by icnocop** [comment]
@Seabizkit you can try to use the `CreateDocumentCacheKey` property on `OpenApiDocumentMiddlewareSettings`.

**Pull request merged**
