### PR TITLE
WIP Custom CSharp single client class operation name generator.

### PR DESCRIPTION
**Pull request by uroshk**
I encountered a problem with ambiguous methods when generating the CSharp client with MultipleClientsFromPathSegments operation name generator. The following swagger definition includes the path '/products/{id}' with HTTP operations GET and DELETE:

[products_json.txt](https://github.com/RSuter/NSwag/files/1355716/products_json.txt)

which will result in the generated Client class having two members with same name and signature:

```csharp
/// <summary>Load by ID</summary>
public async System.Threading.Tasks.Task<ProductDto> ProductsAsync(string id, System.Threading.CancellationToken cancellationToken)
{
    // ...
    request_.Method = new System.Net.Http.HttpMethod("GET");
    // ...
}
```

and

```csharp
/// <summary>Delete an entry</summary>
public async System.Threading.Tasks.Task ProductsAsync(string id, System.Threading.CancellationToken cancellationToken)
{
    // ...
    request_.Method = new System.Net.Http.HttpMethod("DELETE");
    // ...
}
```

The compiler will complain about ambiguous method invocation.

I would like to propose a new client operation name generator implementation, which produces a single client class with members names composed from Swagger path segments suffixed by the respective HTTP operation name.

The following NSwag configuration produces working client code for me.

```
{
  "runtime": "Default",
  "swaggerGenerator": {
    "fromSwagger": {
      "json": "{\r\n    \"swagger\": \"2.0\",\r\n    \"info\": {\r\n        \"version\": \"1.0.6-SNAPSHOT\",\r\n        \"title\": \"ssk-srv\"\r\n    },\r\n    \"basePath\": \"/ssk-srv/api\",\r\n    \"tags\": [\r\n        {\r\n            \"name\": \"products\"\r\n        }\r\n    ],\r\n    \"paths\": {\r\n        \"/products\": {\r\n            \"get\": {\r\n                \"tags\": [\r\n                    \"products\"\r\n                ],\r\n                \"summary\": \"List entries\",\r\n                \"description\": \"\",\r\n                \"operationId\": \"list\",\r\n                \"parameters\": [\r\n                    {\r\n                        \"name\": \"offset\",\r\n                        \"in\": \"query\",\r\n                        \"description\": \"Number of entries to skip\",\r\n                        \"required\": false,\r\n                        \"type\": \"integer\",\r\n                        \"minimum\": 0.0,\r\n                        \"format\": \"int32\"\r\n                    },\r\n                    {\r\n                        \"name\": \"limit\",\r\n                        \"in\": \"query\",\r\n                        \"description\": \"Max number of entries to return\",\r\n                        \"required\": false,\r\n                        \"type\": \"integer\",\r\n                        \"minimum\": 1.0,\r\n                        \"format\": \"int32\"\r\n                    },\r\n                    {\r\n                        \"name\": \"orderBy\",\r\n                        \"in\": \"query\",\r\n                        \"description\": \"Property to order by\",\r\n                        \"required\": false,\r\n                        \"type\": \"string\"\r\n                    },\r\n                    {\r\n                        \"name\": \"ascending\",\r\n                        \"in\": \"query\",\r\n                        \"description\": \"Ascending/descending order\",\r\n                        \"required\": false,\r\n                        \"type\": \"boolean\",\r\n                        \"default\": true\r\n                    }\r\n                ],\r\n                \"responses\": {\r\n                    \"200\": {\r\n                        \"description\": \"successful operation\",\r\n                        \"schema\": {\r\n                            \"type\": \"array\",\r\n                            \"items\": {\r\n                                \"$ref\": \"#/definitions/ProductDto\"\r\n                            }\r\n                        }\r\n                    },\r\n                    \"400\": {\r\n                        \"description\": \"Parameter validation error\",\r\n                        \"schema\": {\r\n                            \"$ref\": \"#/definitions/BaseResponse\"\r\n                        }\r\n                    }\r\n                }\r\n            },\r\n            \"post\": {\r\n                \"tags\": [\r\n                    \"products\"\r\n                ],\r\n                \"summary\": \"Create a new entry\",\r\n                \"description\": \"\",\r\n                \"operationId\": \"create\",\r\n                \"consumes\": [\r\n                    \"application/json\"\r\n                ],\r\n                \"parameters\": [\r\n                    {\r\n                        \"in\": \"body\",\r\n                        \"name\": \"body\",\r\n                        \"required\": false,\r\n                        \"schema\": {\r\n                            \"$ref\": \"#/definitions/NewProductDto\"\r\n                        }\r\n                    }\r\n                ],\r\n                \"responses\": {\r\n                    \"201\": {\r\n                        \"description\": \"successful operation\",\r\n                        \"schema\": {\r\n                            \"$ref\": \"#/definitions/ProductDto\"\r\n                        }\r\n                    },\r\n                    \"400\": {\r\n                        \"description\": \"Validation error\",\r\n                        \"schema\": {\r\n                            \"$ref\": \"#/definitions/BaseResponse\"\r\n                        }\r\n                    }\r\n                }\r\n            }\r\n        },\r\n        \"/products/count\": {\r\n            \"get\": {\r\n                \"tags\": [\r\n                    \"products\"\r\n                ],\r\n                \"summary\": \"Count entries\",\r\n                \"description\": \"\",\r\n                \"operationId\": \"count\",\r\n                \"parameters\": [],\r\n                \"responses\": {\r\n                    \"200\": {\r\n                        \"description\": \"successful operation\",\r\n                        \"schema\": {\r\n                            \"type\": \"integer\",\r\n                            \"format\": \"int64\"\r\n                        }\r\n                    }\r\n                }\r\n            }\r\n        },\r\n        \"/products/{id}\": {\r\n            \"get\": {\r\n                \"tags\": [\r\n                    \"products\"\r\n                ],\r\n                \"summary\": \"Load by ID\",\r\n                \"description\": \"\",\r\n                \"operationId\": \"read\",\r\n                \"parameters\": [\r\n                    {\r\n                        \"name\": \"id\",\r\n                        \"in\": \"path\",\r\n                        \"required\": true,\r\n                        \"type\": \"string\"\r\n                    }\r\n                ],\r\n                \"responses\": {\r\n                    \"200\": {\r\n                        \"description\": \"successful operation\",\r\n                        \"schema\": {\r\n                            \"$ref\": \"#/definitions/ProductDto\"\r\n                        }\r\n                    },\r\n                    \"404\": {\r\n                        \"description\": \"Invalid ID\",\r\n                        \"schema\": {\r\n                            \"$ref\": \"#/definitions/BaseResponse\"\r\n                        }\r\n                    }\r\n                }\r\n            },\r\n            \"put\": {\r\n                \"tags\": [\r\n                    \"products\"\r\n                ],\r\n                \"summary\": \"Update an entry\",\r\n                \"description\": \"\",\r\n                \"operationId\": \"update\",\r\n                \"consumes\": [\r\n                    \"application/json\"\r\n                ],\r\n                \"parameters\": [\r\n                    {\r\n                        \"name\": \"id\",\r\n                        \"in\": \"path\",\r\n                        \"required\": true,\r\n                        \"type\": \"string\"\r\n                    },\r\n                    {\r\n                        \"in\": \"body\",\r\n                        \"name\": \"body\",\r\n                        \"required\": false,\r\n                        \"schema\": {\r\n                            \"$ref\": \"#/definitions/NewProductDto\"\r\n                        }\r\n                    }\r\n                ],\r\n                \"responses\": {\r\n                    \"200\": {\r\n                        \"description\": \"successful operation\",\r\n                        \"schema\": {\r\n                            \"$ref\": \"#/definitions/ProductDto\"\r\n                        }\r\n                    },\r\n                    \"400\": {\r\n                        \"description\": \"Validation error\",\r\n                        \"schema\": {\r\n                            \"$ref\": \"#/definitions/BaseResponse\"\r\n                        }\r\n                    },\r\n                    \"404\": {\r\n                        \"description\": \"Invalid ID\",\r\n                        \"schema\": {\r\n                            \"$ref\": \"#/definitions/BaseResponse\"\r\n                        }\r\n                    }\r\n                }\r\n            },\r\n            \"delete\": {\r\n                \"tags\": [\r\n                    \"products\"\r\n                ],\r\n                \"summary\": \"Delete an entry\",\r\n                \"description\": \"\",\r\n                \"operationId\": \"delete\",\r\n                \"parameters\": [\r\n                    {\r\n                        \"name\": \"id\",\r\n                        \"in\": \"path\",\r\n                        \"required\": true,\r\n                        \"type\": \"string\"\r\n                    }\r\n                ],\r\n                \"responses\": {\r\n                    \"404\": {\r\n                        \"description\": \"Invalid ID\",\r\n                        \"schema\": {\r\n                            \"$ref\": \"#/definitions/BaseResponse\"\r\n                        }\r\n                    }\r\n                }\r\n            }\r\n        }\r\n    },\r\n    \"definitions\": {\r\n        \"JsonNode\": {\r\n            \"type\": \"object\",\r\n            \"properties\": {\r\n                \"binary\": {\r\n                    \"type\": \"boolean\",\r\n                    \"default\": false\r\n                },\r\n                \"valueNode\": {\r\n                    \"type\": \"boolean\",\r\n                    \"default\": false\r\n                },\r\n                \"containerNode\": {\r\n                    \"type\": \"boolean\",\r\n                    \"default\": false\r\n                },\r\n                \"missingNode\": {\r\n                    \"type\": \"boolean\",\r\n                    \"default\": false\r\n                },\r\n                \"object\": {\r\n                    \"type\": \"boolean\",\r\n                    \"default\": false\r\n                },\r\n                \"pojo\": {\r\n                    \"type\": \"boolean\",\r\n                    \"default\": false\r\n                },\r\n                \"number\": {\r\n                    \"type\": \"boolean\",\r\n                    \"default\": false\r\n                },\r\n                \"floatingPointNumber\": {\r\n                    \"type\": \"boolean\",\r\n                    \"default\": false\r\n                },\r\n                \"short\": {\r\n                    \"type\": \"boolean\",\r\n                    \"default\": false\r\n                },\r\n                \"int\": {\r\n                    \"type\": \"boolean\",\r\n                    \"default\": false\r\n                },\r\n                \"long\": {\r\n                    \"type\": \"boolean\",\r\n                    \"default\": false\r\n                },\r\n                \"double\": {\r\n                    \"type\": \"boolean\",\r\n                    \"default\": false\r\n                },\r\n                \"bigDecimal\": {\r\n                    \"type\": \"boolean\",\r\n                    \"default\": false\r\n                },\r\n                \"bigInteger\": {\r\n                    \"type\": \"boolean\",\r\n                    \"default\": false\r\n                },\r\n                \"textual\": {\r\n                    \"type\": \"boolean\",\r\n                    \"default\": false\r\n                },\r\n                \"boolean\": {\r\n                    \"type\": \"boolean\",\r\n                    \"default\": false\r\n                },\r\n                \"integralNumber\": {\r\n                    \"type\": \"boolean\",\r\n                    \"default\": false\r\n                },\r\n                \"nodeType\": {\r\n                    \"type\": \"string\",\r\n                    \"enum\": [\r\n                        \"ARRAY\",\r\n                        \"BINARY\",\r\n                        \"BOOLEAN\",\r\n                        \"MISSING\",\r\n                        \"NULL\",\r\n                        \"NUMBER\",\r\n                        \"OBJECT\",\r\n                        \"POJO\",\r\n                        \"STRING\"\r\n                    ]\r\n                },\r\n                \"float\": {\r\n                    \"type\": \"boolean\",\r\n                    \"default\": false\r\n                },\r\n                \"array\": {\r\n                    \"type\": \"boolean\",\r\n                    \"default\": false\r\n                },\r\n                \"null\": {\r\n                    \"type\": \"boolean\",\r\n                    \"default\": false\r\n                }\r\n            }\r\n        },\r\n        \"NewProductDto\": {\r\n            \"type\": \"object\",\r\n            \"properties\": {\r\n                \"meta\": {\r\n                    \"type\": \"object\"\r\n                }\r\n            }\r\n        },\r\n        \"BaseResponse\": {\r\n            \"type\": \"object\",\r\n            \"properties\": {\r\n                \"status\": {\r\n                    \"type\": \"string\"\r\n                },\r\n                \"message\": {\r\n                    \"type\": \"string\"\r\n                },\r\n                \"details\": {\r\n                    \"type\": \"object\"\r\n                },\r\n                \"time\": {\r\n                    \"type\": \"string\",\r\n                    \"format\": \"date-time\"\r\n                },\r\n                \"errorCode\": {\r\n                    \"type\": \"string\"\r\n                }\r\n            }\r\n        },\r\n        \"ProductDto\": {\r\n            \"type\": \"object\",\r\n            \"properties\": {\r\n                \"id\": {\r\n                    \"type\": \"string\"\r\n                },\r\n                \"meta\": {\r\n                    \"$ref\": \"#/definitions/JsonNode\"\r\n                }\r\n            }\r\n        }\r\n    }\r\n}\r\n",
      "url": "",
      "output": null
    }
  },
  "codeGenerators": {
    "swaggerToCSharpClient": {
      "clientBaseClass": "",
      "generateClientClasses": true,
      "generateClientInterfaces": false,
      "generateDtoTypes": true,
      "injectHttpClient": false,
      "disposeHttpClient": true,
      "generateExceptionClasses": true,
      "exceptionClass": "SwaggerException",
      "wrapDtoExceptions": true,
      "useHttpClientCreationMethod": false,
      "httpClientType": "System.Net.Http.HttpClient",
      "useHttpRequestMessageCreationMethod": false,
      "useBaseUrl": true,
      "generateSyncMethods": false,
      "clientClassAccessModifier": "public",
      "generateContractsOutput": true,
      "contractsNamespace": "IBX.Client.Backend.Ssk.Gen.SskSrv",
      "contractsOutputFilePath": "Backend/Ssk/Gen/SskSrv/ProductsModel.cs",
      "parameterDateTimeFormat": "s",
      "generateUpdateJsonSerializerSettingsMethod": true,
      "serializeTypeInformation": false,
      "className": "{controller}Client",
      "namespace": "IBX.Client.Backend.Ssk.Gen.SskSrv",
      "generateOptionalParameters": false,
      "requiredPropertiesMustBeDefined": true,
      "dateType": "System.DateTime",
      "dateTimeType": "System.DateTime",
      "timeType": "System.TimeSpan",
      "timeSpanType": "System.TimeSpan",
      "arrayType": "System.Collections.ObjectModel.ObservableCollection",
      "dictionaryType": "System.Collections.Generic.Dictionary",
      "classStyle": "Inpc",
      "operationGenerationMode": "SingleClientFromPathSegments",
      "generateDefaultValues": true,
      "generateDataAnnotations": true,
      "excludedTypeNames": [],
      "wrapResponses": false,
      "generateResponseClasses": true,
      "responseClass": "{controller}Response",
      "handleReferences": false,
      "generateImmutableArrayProperties": false,
      "generateImmutableDictionaryProperties": false,
      "output": "Backend/Ssk/Gen/SskSrv/ProductsClient.cs"
    }
  }
}
```

### CODE REVIEW

**Comment by RSuter** [comment]
Thanks for the PR. I think this is a good idea...

My problem is, that MultipleClientsFromPathSegmentsOperationNameGenerator and SingleClientFromPathSegmentsOperationNameGenerator do not behave the same way - one appends the HTTP method (single) and the other doesnt (multiple). 

What if we append the HTTP method only if there are name clashes (can be checked with the `SwaggerDocument document` parameter) in both generators. This would not be a breaking change for MultipleClientsFromPathSegmentsOperationNameGenerator because it would have produced invalid code on clashes. 

What do you think?

**Comment by uroshk** [comment]
I agree with your proposal. Actually I initially thought about that, but I
did the changes in a bit of hurry and did not thoroughly investigate the
existing implementation.




On Oct 4, 2017 15:27, "Rico Suter" <notifications@github.com> wrote:

Thanks for the PR. I think this is a good idea...

My problem is, that MultipleClientsFromPathSegmentsOperationNameGenerator
and SingleClientFromPathSegmentsOperationNameGenerator do not behave the
same way - one appends the HTTP method (single) and the other doesnt
(multiple).

What if we append the HTTP method only if there are name clashes (can be
checked with the SwaggerDocument document parameter) in both generators.
This would not be a breaking change for
MultipleClientsFromPathSegmentsOperationNameGenerator
because it would have produced invalid code on clashes.

What do you think?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/RSuter/NSwag/pull/978#issuecomment-334154463>, or mute
the thread

**Comment by RSuter** [comment]
What is the status of this pr?

**Comment by uroshk** [comment]
WiP (been out on a business trip last week). Detecting collisions based on swagger document is not trivial since operations resulting from specific paths and HTTP methods may only collide when the resulting operation signature matches, as is the case with GET and DELETE by ID in the example provided above.

**Comment by uroshk** [comment]
I am submitting a possible solution to conflicting operations: please see changes in [src/NSwag.CodeGeneration/ClientGeneratorBase.cs](https://github.com/uroshk/NSwag/blob/csharp-singleclientfrompaths/src/NSwag.CodeGeneration/ClientGeneratorBase.cs). I tested it with all four controller/operation name generators and it does produce valid code for all of them.

On the other hand, removing HTTP methods from the generated operation name in SIngleClientFromPathSegments produces client code that is much more unreadable (IMHO) e.g.:

```csharp
    public partial class Client 
    {
        /// <summary>List entries</summary>
        /// <param name="offset">Number of entries to skip</param>
        /// <param name="limit">Max number of entries to return</param>
        /// <param name="orderBy">Property to order by</param>
        /// <param name="ascending">Ascending/descending order</param>
        /// <returns>successful operation</returns>
        /// <exception cref="SwaggerException">A server side error occurred.</exception>
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<ProductDto>> ProductsAsync(int? offset, int? limit, string orderBy, bool? ascending) { ... }

        /// <summary>Create a new entry</summary>
        /// <returns>successful operation</returns>
        /// <exception cref="SwaggerException">A server side error occurred.</exception>
        public System.Threading.Tasks.Task<ProductDto> ProductsAsync(NewProductDto body) { ... }

        public System.Threading.Tasks.Task<long> ProductsCountAsync() { ... }

        public System.Threading.Tasks.Task<ProductDto> ProductsGetAsync(string id) { ... }

        public System.Threading.Tasks.Task ProductsDeleteAsync(string id) { ... }

        /// <summary>Update an entry</summary>
        /// <returns>successful operation</returns>
        /// <exception cref="SwaggerException">A server side error occurred.</exception>
        public System.Threading.Tasks.Task<ProductDto> ProductsAsync(string id, NewProductDto body) { ... }
    }
```
In the above implementation we get three client functions with same name. Compare that to the output of the initially proposed implementation:

```csharp
    public partial class Client 
    {
        /// <summary>List entries</summary>
        /// <param name="offset">Number of entries to skip</param>
        /// <param name="limit">Max number of entries to return</param>
        /// <param name="orderBy">Property to order by</param>
        /// <param name="ascending">Ascending/descending order</param>
        /// <returns>successful operation</returns>
        /// <exception cref="SwaggerException">A server side error occurred.</exception>
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<ProductDto>> ProductsGetAsync(int? offset, int? limit, string orderBy, bool? ascending) { ... }

        /// <summary>Create a new entry</summary>
        /// <returns>successful operation</returns>
        /// <exception cref="SwaggerException">A server side error occurred.</exception>
        public System.Threading.Tasks.Task<ProductDto> ProductsPostAsync(NewProductDto body) { ... }

        public System.Threading.Tasks.Task<long> ProductsCountGetAsync() { ... }

        public System.Threading.Tasks.Task<ProductDto> ProductsGetAsync(string id) { ... }

        /// <summary>Update an entry</summary>
        /// <returns>successful operation</returns>
        /// <exception cref="SwaggerException">A server side error occurred.</exception>
        public System.Threading.Tasks.Task<ProductDto> ProductsPutAsync(string id, NewProductDto body) { ... }

        public System.Threading.Tasks.Task ProductsDeleteAsync(string id) { ... }
    }
```
You may agree that the purpose of operations is more obvious making client methods identification easier, especially when addressing large APIs.

**Comment by RSuter** [comment]
Can you rebase?

**Comment by uroshk** [comment]
Sorry. I did rebase before pushing. Am I missing something?

**Comment by RSuter** [comment]
I dont know but the pr has too many changes.. (?)

**Comment by RSuter** [comment]
I don't like that you change the behavior of the existing generators. This may introduce breaking changes for existing users and we cannot do that... Can't this logic be only implemented in the new generator?

**Comment by uroshk** [comment]
Well, I am just working on a possible solution - I would like to extend the existing IOperationNameGenerator with a new method ResolveConflicts, which can then perform deconfliction or not (just return the original operations list) at the operation name generator level. I will push the update today.

**Comment by RSuter** [comment]
I dont think its a good idea to add this method: First the generation is no longer functional/immutable, the added method breaks existing implementations, and I think a generator should directly generate operation name without conflicts... You know all operations in the generator, so you can directly deconflict it without calling the method after generating all names

**Comment by uroshk** [comment]
In this case I see the problem with the current  responsibility separation between ClientGeneratorBase and specific OperationNameGenerators. At IOperationNameGenerator level we do not see the entire operation model nor do we have all the required information to generate one as we do not get ClientGeneratorBaseSettings in there (please note that we need to compare the resulting method signatures). Unless we implement a completely independent Swagger document parser at that level I do not see an elegant way to solve conflicts.

**Comment by RSuter** [comment]
I think we shouldnt compare signatures but method names because languages other than C# (e.g. TypeScript) do not have method overloads...

**Comment by uroshk** [comment]
I understand. I'll move the conflict resolving logic into the generator.

**Comment by uroshk** [comment]
Latest update: on every invocation of IOperationNameGenerator.GetOperationName the current {path , HTTP method, swagger operation} name is generated from the relative path. Then it is compared against all other swagger operations matching the current client name. In case of conflicts the HTTP method is appended to the name.

**Comment by RSuter** [comment]
Is the PR ready?

**Comment by uroshk** [comment]
The PR is ready.

**Comment by RSuter** [comment]
v11.11.3

**Pull request merged**
