### PR TITLE
Fixes "return null" problem in issue #1509.

### PR DESCRIPTION
**Pull request by pekspro**
Changed so that functions that could return a value also could return null.

### CODE REVIEW

**Comment by RSuter** [comment]
I think you should change `{% if operation.HasResultType %}` to `{% if operation.HasResultType and SupportsStrictNullChecks %}` so that this is only rendered for supported TS versions...

**Comment by RSuter** [comment]
(I know that probably no one still uses that old versions :-)

**Comment by RSuter** [comment]
What do you think? 
Anyway thanks for the PR!

**Comment by pekspro** [comment]
Ah, you’re right :-) I didn’t know such check existed :-) I will change it later today or tomorrow.

**Comment by RSuter** [comment]
Ok, I've made the change. Thanks for the PR!

**Pull request merged**
