### PR TITLE
remove extra parentheses

### PR DESCRIPTION
**Pull request by Y2zz**

### CODE REVIEW

**Comment by RSuter** [comment]
Are you sure this doesnt break things?

**Comment by Y2zz** [comment]
I found it when I used the Fetch template and I tested the build results and it seems to solve my problem.

**Comment by Y2zz** [comment]
image

**Comment by RSuter** [comment]
I've updated the template in this PR so that other output types don't break. Can you retest with that?

**Comment by Y2zz** [comment]
Still not working, but I found the problem.
Because prior to use Angular template, when modified to Fetch templates, profiles, attributes appear in rxjsversion

image

**Comment by Y2zz** [comment]
Forgot to say, I am using NSwagStudio for editing.

**Comment by RSuter** [comment]
I've added an additional IsAngular check, so it must now use the correct path...

**Comment by Y2zz** [comment]
I just tried it, still invalid

**Comment by RSuter** [comment]
You tried with 

```
{% if Framework.IsFetchOrAurelia or operation.RequestAngularBlobs or Framework.Angular.UseHttpClient or operation.RequestAngularJSBlobs -%}
{%     if Framework.IsAngular and Framework.UseRxJs6 and (Framework.Angular.UseHttpClient or operation.RequestAngularBlobs) -%}
}));
{%     else -%}
});
{%     endif -%}
{% endif -%}
```
?

**Comment by Y2zz** [comment]
image

Yes...

**Comment by RSuter** [comment]
How did you try this? Do you override the template via TemplateDirectory? I'm pretty sure the changed template is not picked up correctly...

**Comment by Y2zz** [comment]
Sorry, it’s my problem, my configuration file is overwritten, it works fine after specifying the template folder.

**Pull request merged**
