### PR TITLE
Adds support for deep objects in query parameters.

### PR DESCRIPTION
**Pull request by crfloyd**
This feature adds support for deep object functionality for OpenApi 3.0. Ex:
 `color[R]=100&color[G]=200&color[B]=150`
Reference: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md

### CODE REVIEW

**Comment by RSuter** [comment]
Thanks for the pr, really apprecite it.. hope to get time to look into it soon... Is the template completely changed or is this only a formatting change?

**Comment by crfloyd** [comment]
Hi, the template changed enough to allow the generation of code to accommodate deep object query string Params. I have been using this change off my fork for a couple weeks now. Thanks!

**Comment by RSuter** [comment]
Do you know how this is supported in Asp.net core?

**Comment by RSuter** [comment]
What is explode used for?

**Comment by RSuter** [comment]
I've reformatted the template and used the already available upper converter... does it look good to you?

**Pull request merged**
