### PR TITLE
Fix for .net core 2.2 support in npm package

### PR DESCRIPTION
**Pull request by MarcosMeli**
Adding .net core 2.2 as default runtime
Adding 22 to supportedCoreVersions array

### CODE REVIEW

**Comment by RSuter** [comment]
Had to change the default back to 2.1 as it would be a breaking change...

**Comment by MarcosMeli** [comment]
Perfect @RSuter. I thought that .net core 2.2 runtime will handle 2.1 assemblies with no problem
Good to know for future releases
Thanks

**Comment by RSuter** [comment]
> I thought that .net core 2.2 runtime will handle 2.1 assemblies with no problem

Maybe yes, but you need to have 2.2 installed on the machine (which might not be the case). Also i dont want to take this risk :-)

**Comment by MarcosMeli** [comment]
> > I thought that .net core 2.2 runtime will handle 2.1 assemblies with no problem
> 
> Maybe yes, but you need to have 2.2 installed on the machine (which might not be the case). Also i dont want to take this risk :-)

I completely agree with you

**Pull request merged**
