### PR TITLE
[WIP] Add extension data to document and operations

### PR DESCRIPTION
**Pull request by paulomorgado**

### CODE REVIEW

**Comment by RSuter** [comment]
Can you rebase the branch (too many changes in this PR)?

**Comment by paulomorgado** [comment]
Rebase onto what? master?


In order for this to work for parameters and responses, this should be baked into the parameter and response processor, right?

**Comment by RSuter** [comment]
Ah, this is a pr into the extension-data branch...

**Comment by paulomorgado** [comment]
Hadn't noticed that. I can change to the master branch or you can update the extension-data branch.

**Comment by RSuter** [comment]
Yes, please create a PR against master, extension-data is more than a year old...

**Comment by paulomorgado** [comment]
Done!

**Comment by RSuter** [comment]
> In order for this to work for parameters and responses, this should be baked into the parameter and response processor, right?

Yes, seems a little bad design-wise that half of it is handled by custom processors (controllers/operations) and the other part in an existing processor (response/parameter). Maybe we just "hardcode" this into one processor (same as the other attrs are implemented).

**Comment by paulomorgado** [comment]
I didn't do that because, at that point, I couldn't get to the parameters in a deterministic way.

**Comment by RSuter** [comment]
Added parameter handling and some fixes: https://github.com/RSuter/NSwag/commit/4f324ae17e7f63b9f7be27ba3115a29a4af47f9a

Ok for you?

**Comment by paulomorgado** [comment]
LGTM!

**Pull request merged**
