### PR TITLE
Updated and more efficient Schema Version detection

### PR DESCRIPTION
**Pull request by martinholden-skillsoft**
Updated schema version detection to use RegEx

### CODE REVIEW

**Comment by RSuter** [comment]
Thanks for the PR. I've updated the logic a little bit... is that ok?

**Comment by martinholden-skillsoft** [comment]
Perfect - I was rushing this morning and hadn't had enough coffee before I commited :-)

**Comment by RSuter** [comment]
Why did you close?

**Comment by martinholden-skillsoft** [comment]
Really need that coffee!!!

**Comment by RSuter** [comment]
Ok it's merged, you can get your coffee :) thanks for the PR (with unit tests!!)!

**Pull request merged**
