### PR TITLE
Only generate the blobToText and throwException if it is needed

### PR DESCRIPTION
**Pull request by FreeFrags**
A proposal to fixing the following issue:
https://github.com/RSuter/NSwag/issues/1704

### CODE REVIEW

**Comment by RSuter** [comment]
I think we need a new property, eg RequireClientFunctions without the swaggerexception check for the functions:

https://github.com/RSuter/NSwag/blob/b5a2a2d7195019b846e31b0d36c7058abbab9a1d/src/NSwag.CodeGeneration.TypeScript/Models/TypeScriptFileTemplateModel.cs#L136

**Comment by FreeFrags** [comment]
i might be mistaken but since the client functions require the SwaggerException class,i think that the RequiresClientFunctions function needs to check if RequiresSwaggerExceptionClass returns true. 

Which will then result in the same check as the RequiresSwaggerExceptionClass. 

I will modify the code so you can see what i mean.

**Comment by FreeFrags** [comment]
Would this be the preferred solution?

**Comment by RSuter** [comment]
Yes, that makes sense

**Comment by FreeFrags** [comment]
All right thank you very much, is there anywhere we can see what the estimated date or the open issues remaing till a next release are?

**Comment by RSuter** [comment]
I am currently merging some PRs, test everything and will release a new version in the next days.

**Comment by RSuter** [comment]
I think it should be

```
        /// <summary>Gets a value indicating whether the client functions are required.</summary>
        public bool RequiresClientFunctions => 
            _settings.GenerateClientClasses &&
            !string.IsNullOrEmpty(Clients);

        /// <summary>Gets a value indicating whether the SwaggerException class is required. Note that if RequiresClientFunctions returns true this returns true since the client functions require it. </summary>
        public bool RequiresSwaggerExceptionClass =>
            RequiresClientFunctions &&
            !_settings.TypeScriptGeneratorSettings.ExcludedTypeNames.Contains("SwaggerException");
```

template looks correct.

**Pull request merged**
