### PR TITLE
add a sample project for OWIN Middleware

### PR DESCRIPTION
**Pull request by chucklu**
Hi @RSuter ,
    I have made a sample for this tutorial [OWIN Middleware](https://github.com/RSuter/NSwag/wiki/OWIN-Middleware)
    Related issue list:
https://github.com/RSuter/NSwag/issues/1915
https://github.com/RSuter/NSwag/issues/1924
     I have modified the tutorial several times for missing dependency. Now I want to provide a sample for it.
     If you merge this sample project, then I will add the link on that tutorial.

### CODE REVIEW

**Comment by RSuter** [comment]
I've seen that you reference NSwag via nuget packages not project references - this is fine. But maybe it's better to move the project into the samples/ directory to keep the solution "small" - or better not make it bigger :-)

**Comment by chucklu** [comment]
Hi @RSuter ,
     I have moved the sample project to samples folder.

**Comment by RSuter** [comment]
Thanks for the PR!

**Comment by chucklu** [comment]
There are lots of sample projects under https://github.com/RSuter/NSwag/tree/master/src
Do you have a plan to move them to the samples folder?

**Pull request merged**
