### PR TITLE
Use ReDoc v2 on AspNet.Owin

### PR DESCRIPTION
**Pull request by gymbowfits**
AspNet.Owin is using the previous version of ReDoc and was not updated with the ReDoc v2 changes to AspNetCore.

### CODE REVIEW

**Comment by RSuter** [comment]
Thanks for the PR. Did you test it?

**Comment by gymbowfits** [comment]
Hi,

I haven't performed any formal testing - I don't think that there is anything automated around this either?  I have however performed manual tests through the Sample.NetGlobalAsax  application and haven't encountered any issues.  Let me know if this testing is not sufficient (and if you'd prefer if I raised an issue for something like this prior to initiating a PR!)

I've attached some screenshots of the before and after and using the Swagger2 and OpenApi3 schemas.

Using ReDoc v1 Swagger2 (i.e. previous):
redoc_v1_swagger2

Using ReDoc v1 OpenAPI3 (i.e. previous):
redoc_v1_openapi3

Using ReDoc v2 Swagger2 (i.e. updated):
redoc_v2_swagger2

Using ReDoc v2 OpenAPI3 (i.e. updated):
redoc_v2_openapi3

**Comment by RSuter** [comment]
Yeah, didnt ask for an automated test but a manual one. Looks good, thanks.

**Comment by Rzpeg** [comment]
This isn't in NSwag.AspNet.Owin v 12.0.0, right?

**Comment by RSuter** [comment]
It should be in v12, isnt it?

**Comment by Rzpeg** [comment]
@RSuter 
It still references https://rebilly.github.io/ReDoc/releases/latest/redoc.min.js, which is v 1.22.2 atm.
The change isn't in the v12 branch:
https://github.com/RSuter/NSwag/blob/feature/v12/src/NSwag.AspNet.Owin/ReDoc/index.html

**Comment by RSuter** [comment]
Oh crap, the PR was not merged into master but another feature branch... created a new PR: https://github.com/RSuter/NSwag/pull/1764

**Comment by RSuter** [comment]
Will release a new version tomorrow.

**Comment by RSuter** [comment]
(12.0.1)

**Comment by Rzpeg** [comment]
Good, thanks 👍

**Pull request merged**
