### PR TITLE
Add .Net Core 2.2 Support

### LINKED ISSUE #1663: Add .NET Core 2.2 runtime
- [ ] Update enum
- [ ] Update NPM
- [ ] NSwag.MSBuild.CodeGeneration.targets (see ref)

### LINKED ISSUE #1795: Need .Netcore2.2 Support
Hi,
As you know Microsoft released .netcore 2.2 and we need NSwag to support this runtime.

Thanks in advance.
Regards

### PR DESCRIPTION
**Pull request by MarcosMeli**
Closes #1663 closes #1795

### CODE REVIEW

**Comment by MarcosMeli** [comment]
Lilnks for code review:

**Main Changes**

https://github.com/RSuter/NSwag/pull/1799/commits/de338a69675f8058a33c75bd76c747ee760df462
https://github.com/RSuter/NSwag/pull/1799/commits/10313f6e5096e565da4781129cc5eacf42cfd3a0

**Example Project**

https://github.com/RSuter/NSwag/pull/1799/commits/02af17c22a00fc0b82408f8e5bd0cc91c2d2ac17

**Comment by MarcosMeli** [comment]
Build Scripts updated https://github.com/RSuter/NSwag/pull/1799/commits/bdc67c964de8023fc513f445b4ab8e3b99a92c39

**Comment by RSuter** [comment]
Thanks for the pr. You hit almost everything.

Todo: Update nswagstudio project’s post build

Todo: Check CI build in appveyor

**Comment by MarcosMeli** [comment]
Great !! I will do that, and try to help in next .net core upgrades

**Comment by RSuter** [comment]
I already pushed the changes. Now i need to check whether AppVeyor is already able to build .net core 2.2 projects ;)

**Comment by RSuter** [comment]
Ok, PR looks good when running/building locally :-)

**Comment by MarcosMeli** [comment]
> Ok, PR looks good when running/building locally :-)

Yep It builds from me with last SDK, Installer project fails for me because is no installed on my machine

**Comment by MarcosMeli** [comment]
No SDK installed yet in appveyor

error NETSDK1045: The current .NET SDK does not support targeting .NET Core 2.2.  Either target .NET Core 2.1 or lower, or use a version of the .NET SDK that supports .NET Core 2.2. [C:\projects\nswag-25x6o\src\NSwag.ConsoleCore\NSwag.ConsoleCore.csproj]

**Comment by RSuter** [comment]
CI looks good: https://ci.appveyor.com/project/rsuter/nswag-25x6o/builds/20823633

**Comment by MarcosMeli** [comment]
I will take the artifacts and test the NSwagStudio

**Comment by RSuter** [comment]
Thanks. But keep in mind that it uses still the old version but is actually a new version :)

**Comment by MarcosMeli** [comment]
All works as expected, angular output generated.

We just need to migrate to another input method soon

image

**Comment by khaninejad** [comment]
Thanks for an update

**Comment by MarcosMeli** [comment]
Hi @RSuter there is something wrong with the npm package

If I run nswag run version /runtime:NetCore22 i get:

image

I will investigate what I miss in the changes

**Comment by MarcosMeli** [comment]
Yes indeed a missing value in supportedCoreVersions array

https://github.com/RSuter/NSwag/pull/1812

**Comment by RSuter** [comment]
Thanks for all your PRs. Great work and everything looks good.

**Comment by MarcosMeli** [comment]
Is an honor to help, thanks to you !!

NPM Validated:

image

**Comment by qwertykeith** [comment]
thanks for this! :) 
is the fix available on nuget? (sorry i don't know how to work that out yet)

**Comment by RSuter** [comment]
Yes it is

**Pull request merged**
